
// class trycatch
// {
//     static void Main(String[] args)
//     {
//         try
//         {
//             int a = 5;
//             int b = 0;
//             Console.WriteLine(a / b);
//         }
//         catch (DivideByZeroException dex)
//         {
//              Console.WriteLine("Divide By Zero Exception: " + dex.Message);
//         }
//         catch(Exception ex)
//         {
//             Console.WriteLine("General Exception: " + ex.Message);    
//         }
//         finally
//         {
//             Console.WriteLine();
//             Console.WriteLine("This is always called, whatever it has exception!");
//         }
//     }
// }
